config/routes.rb
Rails.application.routes.draw do
  get 'bookings/index'
  get 'costumes/index'
  devise_for :users
  root to: "pages#home"


  resources :costumes do
    collection do
      get :my_costumes
    end
    resources :bookings, only: [:index, :create]
  end

  resources :users, only: [:show, :edit, :update]

  resources :bookings, only: [:destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :costume
  validates :start_date, :end_date, presence: true
end

app/models/costume.rb
class Costume < ApplicationRecord
  belongs_to :user
  include PgSearch::Model
  pg_search_scope :search_by_name_and_desc_and_type,
  against: [ :product_name, :details, :pet_type],
  using: {
    tsearch: { prefix: true }  }
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :product_name, :price, :photo, :pet_type, presence: true
  validates :pet_type, inclusion: { in: ["cat", "dog", "bird", "reptile", "small mammal"] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :costumes, dependent: :destroy
  has_many :bookings
  validates :email, presence: true, uniqueness: true
  # validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def create
    @costume = Costume.find(params[:costume_id])
    @booking = Booking.new(booking_params)
    @booking.costume = @costume
    @booking.user_id = current_user.id
    if @booking.save
      redirect_to bookings_index_path
    else
      render :new, status: unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_index_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :message)
  end
end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  def index
    if params[:query].present?
      @costumes = Costume.search_by_name_and_desc_and_type(params[:query])
    else
      @costumes = Costume.all
    end
  end

  def show
    @costume = Costume.find(params[:id])
    @booking = Booking.new
  end

  def new
    @costume = Costume.new
  end

  def create
    @costume = Costume.new(costume_params)
    @costume.user_id = current_user.id

    if @costume.save
      redirect_to costumes_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @costume = Costume.find(params[:id])
  end

  def update
    @costume = Costume.find(params[:id])
    if @costume.update(costume_params)
      redirect_to my_costumes_costumes_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def my_costumes
    @costumes = Costume.where(user_id: current_user.id)
    @bookings = Booking.all
  end

  def destroy
    @costume = Costume.find(params[:id])
    @costume.destroy
    redirect_to my_costumes_costumes_path, status: :see_other
  end

  private

  def costume_params
    params.require(:costume).permit(:product_name, :img, :photo, :details, :price, :pet_type, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :address, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <div class="booking-heading-card">
    <h1>Bookings</h1>
    <p>See the bookings you've made!</p>
  </div>


<div class="row">
  <% @bookings.each do |booking| %>
    <% if booking.user_id == current_user.id  %>
      <div class="booking-card col-4">
        <div class="booking-card-img">
          <%= link_to cl_image_tag(booking.costume.photo.key, gravity: :face, crop: :fill), costume_path(booking.costume) %>
        </div>
        <div class="booking-card-info">
              <h2><%= link_to booking.costume.product_name, costume_path(booking.costume), class: "booking-link" %></h2>
              <p><%= booking.start_date %> to <%= booking.end_date %>
              <%= link_to booking_path(booking), data:{turbo_method: "delete", turbo_confirm: "Are you sure?"} do %>
               <i class="fa-solid fa-trash"></i>
               <% end %>
              </p>
        </div>
      </div>
    <% end %>
  <% end %>

  </div>
    <%= link_to "Back to all costumes", costumes_path, class: "button" %>
  </div>

app/views/costumes/edit.html.erb
<h1 class="header-one">Edit Your Cute Lil Cossy</h1>

<div class="new-container">


  <div>
    <%= simple_form_for @costume do |f| %>
    <h2 class="form-title">Edit your costume details...</h2>
      <%= f.input :product_name %>
      <%= f.input :photo, as: :file %>
      <%= f.input :details %>
      <%= f.input :price %>
      <%= f.input :pet_type, collection: ["cat", "bird", "dog", "reptile", "small mammal"] %>
      <%= f.submit 'Edit Costume', class: 'button', id:'form-submit-btn' %>

    <% end %>
  </div>
</div>

app/views/costumes/index.html.erb
<div class="container">
  <div>
    <h1>Costumes</h1>
    <p>View our full range of fancy finery for your fabulous fur baby...</p>
  </div>

  <style>
    @import url('https://fonts.googleapis.com/css2?family=Crimson+Text&display=swap');
  </style>


  <%= form_with url: costumes_path, method: :get, class: "d-flex search-bar mb-5" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control search-input",
      placeholder: "Find a costume"
    %>
    <%= submit_tag "Search", class: "button m-0" %>
  <% end %>

    <div class="card-trip row row-cols-1 row-cols-md-3 g-4 h-200 shadow p-3 mb-5 bg-body rounded">
    <% @costumes.each do |costume| %>
      <div class="col-md-3">
        <div class="card h-100">
          <%= link_to costume_path(costume) do %>
            <%= cl_image_tag costume.photo.key, class: 'card-img-top'%>
          <% end %>
          <div class="card-body d-flex flex-column" style="justify-content: space-between; align-contents: center">
            <h2 class="card-title"><%= costume.product_name %></h2>
              <div class="d-flex" style="justify-content: space-between; margin-top:auto, align-contents: center">
              <p>
              <% if costume.pet_type == "cat" %>
                <i class="fa-solid fa-cat"></i>
              <% elsif costume.pet_type == "dog" %>
                <i class="fa-solid fa-dog"></i>
              <% elsif costume.pet_type == "bird" %>
                <i class="fa-solid fa-dove"></i>
              <% elsif costume.pet_type == "small mammal" %>
                <i class="fa-solid fa-carrot"></i>
              <% elsif costume.pet_type == "reptile" %>
                <i class="fa-solid fa-dragon"></i>
              <% end %>
              </p>
               <p> £<%= '%.2f' % costume.price%></p>
               </div>

            <%= link_to "Info", costume_path(costume), class: "button"%>
          </div>

        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/costumes/my_costumes.html.erb
<div class="container">
	<div class="costumes-header-card">
		<h1>My costumes!</h1>

		<p>Here you can see all of your costumes and the upcoming bookings for them!</p>

			<%= link_to "List a new costume", new_costume_path, class: "button" %>
	</div>

		<div class="row row-cols-1 row-cols-md-3 g-4 h-200 shadow p-3 mb-5 bg-body rounded">
			<% @costumes.each do |costume| %>
				<% if costume.user_id == current_user.id  %>
				<% end %>
				<div class="col-md-3">
					<div class="card h-100">
						<%= link_to costume_path(costume) do %>
							<%= cl_image_tag costume.photo.key, class: 'card-img-top'%>
							<div class="card-body d-flex flex-column" style="justify-content: space-between" >
						<% end %>
								<h1 class="card-title"><%= costume.product_name %></h1>
								<br>
								<p class="card-text" style="text-align: center; margin-top: auto">
									<%= link_to edit_costume_path(costume) do %>
										<i class="fa-solid fa-pencil"></i>
									<% end %>
										<%= link_to costume_path(costume), data:{turbo_method: "delete", turbo_confirm: "Are you sure?"} do %>
											<i class="fa-solid fa-trash"></i>
										<% end %>
								</p>
								<%= link_to "Info", costume_path(costume), class: "homepage-btn" %>
							</div>
					</div>
				</div>
			<%end%>
		</div>

		<div>
			<h2 class="mb-4">Bookings for my costumes</h2>

			<div class="row row-cols-1 row-cols-md-3 g-4 h-200 shadow p-3 mb-5 bg-body rounded">
				<% @bookings.each do |booking| %>
					<% if booking.costume.user_id == current_user.id  %>
            <div class="booking-card col-4">
              <div class="booking-card-img">
                <%= cl_image_tag booking.costume.photo.key%>
              </div>
              <div class="booking-card-info">
                <h2><%= link_to booking.costume.product_name, costume_path(booking.costume), class: "booking-link" %></h2>
                <p><%= booking.start_date %> to <%= booking.end_date %>
                <br>Booked by <%= booking.user.first_name %>
                <br>Message: "<%= booking.message %>"
                </div>
            </div>
					<% end %>
				<% end %>
			</div>
       <div class="button-card">
			  <%= link_to "Back to all costumes", costumes_path, class: "button" %>
       </div>
</div>

app/views/costumes/new.html.erb
<h1 class="header-one">Add A New Cossy</h1>

<div class="new-container">


<div>
<%= simple_form_for @costume do |f| %>
<h2 class="form-title">list a new costume</h2>
  <%= f.input :product_name %>
  <%= f.input :photo, as: :file %>
  <%= f.input :details %>
  <%= f.input :price %>
  <%= f.input :pet_type, collection: ["cat", "bird", "dog", "reptile", "small mammal"] %>
  <%= f.submit 'Add Costume', class: 'button', id:'form-submit-btn' %>

<% end %>
</div>
</div>

app/views/costumes/show.html.erb
<div class="container">
      <div class= "costume-title" style="align-self:start;">
        <h1><%= @costume.product_name %> </h1>
      </div>
  <div class="row mb-4">
    <div class="col-sm-6 d-flex flex-column align-items-center">

      <div class= "costume-img">
        <%= cl_image_tag @costume.photo.key %>
      </div>
      
      <div class="card-info">
        <div>
          <p class="description"> For your gorgeous <%= @costume.pet_type %><p>
          <p class="details"> <%= @costume.details %></p>
        </div>
        <h4 class= "price "> £ <%= '%.2f' % @costume.price %></h4>
      </div>
    </div>

    <div class="col-sm-6 d-flex flex-column align-items-center">
      <div id="booking-box" class= "booking-form">
        <h2>Book this sweet costume</h2>
        <%= simple_form_for [@costume, @booking] do |f| %>
          <%= f.input :start_date, as: :date, html5: true %>
          <%= f.input :end_date, as: :date, html5: true %>
          <%= f.input :message%>
          <%= f.submit :Book, class: 'btn homepage-btn'%>
        <% end %>
      </div>
    </div>
  </div>
</div>


<%= link_to "Back to all costumes", costumes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fancy Fur Babies</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <div class="home-container">

      <div class="navbar navbar-expand-sm navbar-light navbar-FFB d-flex" style="align-contents: center">
        <div class="container-fluid", style="margin-right: 10px">
          <%= link_to costumes_path, class: "navbar-brand" do %>
            <%= image_tag "Logo-FFB.png" %>
          <% end %>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
              <li class="nav-item active">
                <strong><%= link_to "All costumes", costumes_path, class: "nav-link nav-btn" %></strong>
              </li>
              <% if user_signed_in? %>
                <li class="nav-item dropdown">
                  <%= image_tag "Hamburger-FFB.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <%= link_to "Manage My Costumes", my_costumes_costumes_path, class: "dropdown-item"%>
                    <%= link_to "Manage My Bookings", bookings_index_path, class: "dropdown-item" %>
                    <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
                    <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
                  </div>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Login", new_user_session_path, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
      <div id="space-below-navbar">
      </div>
      <%= yield %>
      <div class="footer">
        <div class="footer-links">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
        <div class="footer">
          This footer is made with <i class="fas fa-heart"></i> by Mind Mission
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-img and text">
  <%= image_tag "homepage-dog.jpg", class: "logo", :style => "margin-top: 50px" %>
  <div class= "home-text">
    <h1>Welcome to Fancy Fur Babies!</h1>
    <p>We have a wide array of exquisite costumes for all your precious creatures!</p>
  </div>
  <div>
    <%# <button class="btn homepage-btn">Enter!</button> %>
    <%= link_to "Enter!", costumes_path, class: "btn homepage-btn"  %>
  </div>
</div>






  <%# <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, %>
  <%# class: "dropdown-item" %>

app/views/users/edit.html.erb
<h1>Edit my details</h1>
<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :address %>
  <%= f.input :email %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div>
  <h1>My profile</h1>

  <p>First name: <%= @user.first_name %></p>
  <p>Last name: <%= @user.last_name %></p>
  <p>Address: <%= @user.address %></p>
  <p>Email: <%= @user.email %></p>

  <%= link_to "Edit my profile", edit_user_path(@user) %>
</div>